### ISSUE TITLE
Props to control start position and exit delay

### ISSUE THREAD

**Issue by afif-nass** [dhimankamal/svelte-progressbar#2]
Thank you for the awesome component.

I'd like to request two new props:

1. `startPosition`: A Number between 0 and 1 that controls the x-position the progress bar starts at.
2. `exitDelay`: A Number that controls the progress bar exit delay in milliseconds after navigation ends.

**Comment by dhimankamal** [comment]
Hey new props are added 😊

**Comment by afif-nass** [comment]
Thank you for the fast push, @dhimankamal. The delay prop works; but on my end the progress bar now does not go all the way to the end (regardless if startPosition is set).

**Comment by dhimankamal** [comment]
Hi @afif-nass, please share screen record video ?

**Comment by afif-nass** [comment]
@dhimankamal video is attached.

Component was used as follows:
`<ProgressBar exitDelay={0} color={twConfig.theme.colors.primary} height="0.4rem" />`

https://github.com/dhimankamal/svelte-progressbar/assets/47398601/13ae2373-8568-4a13-b8e5-0c62c6a23e76

**Comment by dhimankamal** [comment]
Hi @afif-nass , this is also fix I publish new version. Check now

**Comment by afif-nass** [comment]
@dhimankamal works well when delay is not set. Same issue when delay is set. Try setting delay to 50 to reproduce the issue.

**Comment by dhimankamal** [comment]
Hi @afif-nass , check now
